C PROGRAM DEMONSTRATING PRINTING 2D ARRAYS IN FORTRAN 77

      PROGRAM ARRAY2D
      IMPLICIT NONE
      INTEGER ROW,COL
      PARAMETER(ROW=5,COL=7)
      CHARACTER ARR(ROW,COL)

C INITIALIZE ARRAY
      CALL IA(ARR,ROW,COL)
C PRINT ARRAY
      CALL PR(ARR,ROW,COL)
      STOP
      END
