C SUBROUTINE TO INITIALIZE A 2D ARRAY
C A IS A 2D ARRAY; R=ROWS,C=COLS
      SUBROUTINE IA(A,R,C)
      IMPLICIT NONE
      INTEGER I,J,R,C
      CHARACTER A(R,*)

      DO 20 I=1,R,1
      DO 10 J=1,C,1
      A(I,J)='.'
10    CONTINUE
20    CONTINUE

      RETURN
      END
