C SUBROUTINE TO PRINT 2D ARRAY
C A IS A 2D ARRAY,R=ROWS,C=COLS
      SUBROUTINE PR(A,R,C)
      IMPLICIT NONE
      INTEGER R,C,I,J
      CHARACTER A(R,*), LINE(C) 
C LINE IS CHRACTER BUFFER

      DO 40 I=1,R,1
      DO 30 J=1,C,1
      LINE(J) = A(I,J) 
30    CONTINUE
      WRITE(*,*) LINE
40    CONTINUE

      RETURN
      END
