C PROGRAM TO CALCULATE X VALUES OF QUADRATIC EQUATION

C SUBROUTINE TO CALCULATE XNEG,XPOS of QUADRATIC EQUATION
C ALLOWS COMPLEX ANSWERS (DOUBLEPRECISION COMPLEX)
      SUBROUTINE CDQ(A,B,C)
      IMPLICIT NONE
      DOUBLEPRECISION A,B,C
      DOUBLE COMPLEX XNEG,XPOS
      COMMON/X/ XNEG,XPOS

      XNEG=(DCMPLX(-B)-CDSQRT(DCMPLX(B**2-4.0*A*C)))/DCMPLX(2.0*A)
      XPOS=(DCMPLX(-B)+CDSQRT(DCMPLX(B**2-4.0*A*C)))/DCMPLX(2.0*A)

      RETURN
      END
C END OF DQUAD

C MAIN PART OF PROGRAM
      PROGRAM CQUAD
      IMPLICIT NONE
      DOUBLEPRECISION A,B,C
      DOUBLE COMPLEX XNEG, XPOS
      COMMON/X/ XNEG,XPOS

C GET A,B,C
      WRITE(*,*) 'A,B,C:'
      READ(*,*) A,B,C

      CALL CDQ(A,B,C)
      WRITE(*,*) 'XNEG=',XNEG
      WRITE(*,*) 'XPOS=',XPOS
      STOP
      END
C END OF MAIN PART OF PROGRAM
