C A ROCK IS THROWN INTO A WELL 214 METERS DEEP (D) AT AN INITIAL 
C VELOCITY OF 4M/S (V0). HOW LONG (T) WILL IT TAKE THE ROCK TO HIT THE	
C BOTTOM OF THE WELL
C D=.5*G*T**2+V0*T

C START OF DQUAD
      SUBROUTINE DQUAD(A,B,C)
      IMPLICIT NONE
      DOUBLEPRECISION A,B,C,XNEG,XPOS
      COMMON/X/ XNEG,XPOS

      XNEG=(-B-DSQRT(B**2-4.0*A*C))/(2.0*A)
      XPOS=(-B+DSQRT(B**2-4.0*A*C))/(2.0*A)
      RETURN
      END
C END OF DQUAD

      PROGRAM FALL
      IMPLICIT NONE
      DOUBLEPRECISION D,T,V0,G,A,B,C,XNEG,XPOS
      PARAMETER(G=9.81,D=214.0)
      COMMON/X/ XNEG,XPOS 
C G ACCELERATION DUETO GRAVITYT

      V0=4.0
      A=.5*G
      B=V0
      C=-D

      CALL DQUAD(A,B,C)
      WRITE(*,*) XNEG,XPOS
      STOP
      END
