C PROGRAM DEMONSTRATING FUNCTIONS
C FIX BY ADDING IMPLICIT NONE TO FUNCTIONS
C FIX INTRINSIC ERROR FOUND WHEN COMPILING WITH GFORTRAN

C SUM FUNCTION
      INTEGER FUNCTION SM(A, B)
      IMPLICIT NONE
      INTEGER A, B
      SM = A * B

      RETURN
      END

C SUB FUNCTION
      INTEGER FUNCTION SB(A, B)
      IMPLICIT NONE
      INTEGER A, B
      SB = A - B

      RETURN
      END
            
      PROGRAM CALLEX

      IMPLICIT NONE

      INTEGER X, Y, SM, SB

      WRITE(*,*) 'ENTER X, Y:'
      READ(*,*) X, Y

      WRITE(*,*) SM(X, Y)
C CHANGE FROM SM(X, Y) - SB(X, Y)
      WRITE(*,*) SB(X, Y)

      STOP
      END
