C STRUCTURES AREN'T A STANDARD FEATURE IN FORTRAN 77
C THIS WAS COMPILED WITH GFORTAN COMPILER IN LINUX
C GFORTRAN -STD=LEGACY -FDEC-STRUCTURE -G -WALL -WERROR -WEXTRA -WCONVERSION STRUCT.F -O STRUCT
C ALL LOWERCASE EXCEPT 1ST LETTER IN -WALL, -WERROR, -WEXTRA, AND -WCONVERSION ARE CAPITAL

C SUBROUTINE TO PRINT OBJ STRUCTURE ELEMENTS
      SUBROUTINE POBJ(A,I,D)
      IMPLICIT NONE
      CHARACTER A
      INTEGER I
      DOUBLEPRECISION D
      WRITE(*,'(A2,A)') 'A=',A
      WRITE(*,'(A2,I4)') 'I=',I
      WRITE(*,'(A2,F8.2)') 'D=',D

      RETURN
      END

      PROGRAM STRUCT
      IMPLICIT NONE

      STRUCTURE /OBJ/
         CHARACTER A
         INTEGER I
         DOUBLEPRECISION D
      END STRUCTURE

      RECORD /OBJ/ OBJ1,OBJ2,OBJ3

C INIT OBJ1
      OBJ1.A='A'
      OBJ1.I=6
      OBJ1.D=69.0
C INIT OBJ2
      OBJ2.A='B'
      OBJ2.I=12
      OBJ2.D=56.7
C INIT OBJ3
      OBJ3.A='C'
      OBJ3.I=35
      OBJ3.D=99.3

C PRINT OBJ STRUCTURES
      WRITE(*,*) 'OBJ1' 
      CALL POBJ(OBJ1.A,OBJ1.I,OBJ1.D)
      WRITE(*,*)
      WRITE(*,*) 'OBJ2'
      CALL POBJ(OBJ2.A,OBJ2.I,OBJ2.D)
      WRITE(*,*)
      WRITE(*,*) 'OBJ3'
      CALL POBJ(OBJ3.A,OBJ3.I,OBJ3.D)

      STOP
      END

