C PROGRAM TO CREATE PSUDO-RANDOM NUMBERS
C USING LINEAR CONGRUENCE METHOD

      PROGRAM MAIN
      IMPLICIT NONE
      INTEGER SEED,I,N,TEST(10),LN,IN
      PARAMETER(N=200)
      DOUBLEPRECISION X(N)
C X IS AN ARRAY OF RANDOM NUMBERS
C TEST IS AN ARRAY TO HOLD THE OCCURANCE OF EACH NUMBER (0 TO 9)
C LN IS THE LINE COUNT
C IN IS INPUT (FOR PRINT)
      SEED=12345.0
      DATA TEST/10 * 0/
      LN=0

C GENERATE N RANDOM NUMBERS      
      DO 20 I=1,N,1
      CALL DRAND(X,N,SEED)
20    CONTINUE

C PRINT ARR (RANDOM INTEGER NUMBERS from 0 TO 9)
      DO 30 I=1,N,1
      WRITE(*,*) 'I=',I,INT(10.0*X(I))

C PROMPT USER FOR INPUT EVERY 20 LINES (TO MAKE IT ENTIRELY VIEWABLE)
      IF((MOD(LN,20) .EQ. 0) .AND. (LN .NE. 0)) THEN
        WRITE(*,*) 'ENTER A INTEGER TO CONTINUE'
        READ(*,*) IN
      ENDIF

C TEST COUNT OCURRANCE OF EACH NUMBER (0 TO 9)
      IF(INT(10.0*X(I)) .EQ. 0) THEN
        TEST(1)=TEST(1)+1
      ELSEIF(INT(10.0*X(I)) .EQ. 1) THEN
        TEST(2)=TEST(2)+1
      ELSEIF(INT(10.0*X(I)) .EQ. 2) THEN
        TEST(3)=TEST(3)+1
      ELSEIF(INT(10.0*X(I)) .EQ. 3) THEN
        TEST(4)=TEST(4)+1
      ELSEIF(INT(10.0*X(I)) .EQ. 4) THEN
        TEST(5)=TEST(5)+1
      ELSEIF(INT(10.0*X(I)) .EQ. 5) THEN
        TEST(6)=TEST(6)+1
      ELSEIF(INT(10.0*X(I)) .EQ. 6) THEN
        TEST(7)=TEST(7)+1
      ELSEIF(INT(10.0*X(I)) .EQ. 7) THEN
        TEST(8)=TEST(8)+1
      ELSEIF(INT(10.0*X(I)) .EQ. 8) THEN
        TEST(9)=TEST(9)+1
      ELSEIF(INT(10.0*X(I)) .EQ. 9) THEN
        TEST(10)=TEST(10)+1
      ENDIF

      LN=LN+1
30    CONTINUE

C PRINT RESULT
      DO 50 I=1,10,1
      WRITE(*,*) I-1, ' OCCURED ', TEST(I), ' TIMES'
50    CONTINUE

      STOP
      END
