C SUBOUTINE TO GENERATE N DOUBLEPRECISION RANDOM NUMBERS BETWEEN 0 & 1
      SUBROUTINE DRAND(ARR,N,SEED)
      IMPLICIT NONE
      INTEGER SEED,I,N
      DOUBLEPRECISION ARR(*),A,C,M
      PARAMETER(A=65535.0,C=1.0, M=2.0**31-1)

      ARR(1) = DMOD(A*DBLE(SEED)+C,M)

      DO 10 I=2,N,1
      ARR(I) = DMOD(A*ARR(I-1)+C,M)
10    CONTINUE

      DO 15 I=1,N,1
      ARR(I) = ARR(I)/M
15    CONTINUE

      RETURN
      END
